package Modelo;

public enum AccionRobot {
    AGENDAR_CITA_MEDICA, ASEAR_DORMITORIO, ELABORAR_LISTA_ALIMENTOS_A_COMPRAR, REGAR_PLANTAS, DAR_PASEO_CON_CIUDADANO,
    ASISTIR_CIUDADANO_REUNION_EN_OTRO_EDIFICIO_INTELIGENTE;
}
